### ISSUE TITLE
One has an error when running，‘’Index in position 2 exceeds array bounds. Index must not exceed 16.

### ISSUE THREAD

**Issue by ikhblo** [RanXu2001/IRS-OTFS-System-Project#1]
![image](https://user-images.githubusercontent.com/67190477/223364749-75611cfc-694f-4c32-99b2-bcc70187f2b0.png)
when i run the OTFS_sample_code file,Can you tell me how to modify it, thank you

**Comment by RanXu2001** [comment]
It might be an issue caused by speed or delay and Doppler bins (i.e. N and M). You can set these 3 parameters. I suppose you can set N and M larger and speed lower. But since the MP detector is of high complexity, large N and M may be time-wasting. 
So it just a trade off.

**Comment by ikhblo** [comment]
> 

I set M,N to 8 and it works successfully,thank you
